security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'bcrypt'

    providers:
        users_in_database:
            entity:
                class: App\Entity\User
                property: EMAIL

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # Form login with the custom authenticator
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: EMAIL
                password_parameter: motdepasse
                enable_csrf: true
            logout:
                path: /logout
                target: /login
            custom_authenticator: App\Security\UserAuthenticator
            # Define the entry point to use the custom authenticator for anonymous access
            entry_point: App\Security\UserAuthenticator  # Explicitly set the entry point for this firewall

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
