services:
    # Register ReCaptchaService explicitly
    App\Service\ReCaptchaService:
        arguments:
            $httpClient: '@http_client'  # Automatically injected HttpClient service
            $secretKey: '%env(GOOGLE_RECAPTCHA_SECRET_KEY)%'  # Secret key from environment

    # Register UserController with explicit dependencies on ReCaptchaService
    App\Controller\UserController:
        arguments:
            $recaptchaService: '@App\Service\ReCaptchaService'

    # Register Recaptcha3Type form with the required arguments
    Karser\Recaptcha3Bundle\Form\Recaptcha3Type:
        arguments:
            $siteKey: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'  # Public key for reCAPTCHA
            $host: 'https://www.google.com/recaptcha/api.js'  # The reCAPTCHA script URL
            $enabled: true  # Whether reCAPTCHA is enabled or not

    # Register UserAuthenticator with the required argument (urlGenerator)
    App\Security\UserAuthenticator:
        arguments:
            $urlGenerator: '@router'

    # Enable autowiring and autoconfiguration globally
    _defaults:
        autowire: true
        autoconfigure: true

parameters:
    # Define your reCAPTCHA keys
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    google_recaptcha_secret_key: '%env(GOOGLE_RECAPTCHA_SECRET_KEY)%'
