services:

    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    # Register ReCaptchaService explicitly
    App\Service\ReCaptchaService:
        arguments:
            $httpClient: '@http_client'  # Automatically injected HttpClient service
            $secretKey: '%env(GOOGLE_RECAPTCHA_SECRET_KEY)%'  # Secret key from environment

    App\Controller\AuthYsfController:
        autowire: true  # Enable autowiring
        autoconfigure: true

    # Register UserController with explicit dependencies on ReCaptchaService
    App\Controller\UserController:
        arguments:
            $recaptchaService: '@App\Service\ReCaptchaService'

    # Register Recaptcha3Type form with the required arguments
    Karser\Recaptcha3Bundle\Form\Recaptcha3Type:
        arguments:
            $siteKey: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'  # Public key for reCAPTCHA
            $host: 'https://www.google.com/recaptcha/api.js'  # The reCAPTCHA script URL
            $enabled: true  # Whether reCAPTCHA is enabled or not

    # Register UserAuthenticator with the required argument (urlGenerator)
    App\Security\UserAuthenticator:
        arguments:
            $urlGenerator: '@router'

    # Register repository services
    App\Repository\:
        resource: '../src/Repository'
        tags: ['doctrine.repository_service']

    # Register the custom Argument Resolver for user lookup by email
    App\ArgumentResolver\UserByEmailValueResolver:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    # Enable autowiring and autoconfiguration globally
    _defaults:
        autowire: true
        autoconfigure: true

parameters:
    # Define your reCAPTCHA keys
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    google_recaptcha_secret_key: '%env(GOOGLE_RECAPTCHA_SECRET_KEY)%'
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

